// <auto-generated />
using System;
using AP.MyGameStore.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyGameStore.Migrations
{
    [DbContext(typeof(MyGameStoreContext))]
    [Migration("20231109101011_MultiStoreSeeding")]
    partial class MultiStoreSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyGameStore.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EmailAddress");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("tblPeople", "Person");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "a@b.com",
                            EmployerId = -1,
                            FirstName = "Jan",
                            Gender = 1,
                            LastName = "Janssens"
                        });
                });

            modelBuilder.Entity("MyGameStore.Model.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Addition")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Place");

                    b.Property<bool>("IsFranchiseStore")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tblStores", "Store");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 1",
                            Number = "3A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -2,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 2",
                            Number = "6A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -3,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 3",
                            Number = "9A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -4,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 4",
                            Number = "12A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -5,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 5",
                            Number = "15A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -6,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 6",
                            Number = "18A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -7,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 7",
                            Number = "21A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -8,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 8",
                            Number = "24A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -9,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 9",
                            Number = "27A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -10,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 10",
                            Number = "30A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -11,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 11",
                            Number = "33A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -12,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 12",
                            Number = "36A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -13,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 13",
                            Number = "39A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -14,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 14",
                            Number = "42A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -15,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 15",
                            Number = "45A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -16,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 16",
                            Number = "48A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -17,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 17",
                            Number = "51A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -18,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 18",
                            Number = "54A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -19,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 19",
                            Number = "57A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -20,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 20",
                            Number = "60A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -21,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 21",
                            Number = "63A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -22,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 22",
                            Number = "66A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -23,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 23",
                            Number = "69A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -24,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 24",
                            Number = "72A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -25,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 25",
                            Number = "75A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -26,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 26",
                            Number = "78A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -27,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 27",
                            Number = "81A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -28,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 28",
                            Number = "84A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -29,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 29",
                            Number = "87A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -30,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 30",
                            Number = "90A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -31,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 31",
                            Number = "93A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -32,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 32",
                            Number = "96A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -33,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 33",
                            Number = "99A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -34,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 34",
                            Number = "102A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -35,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 35",
                            Number = "105A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -36,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 36",
                            Number = "108A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -37,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 37",
                            Number = "111A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -38,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 38",
                            Number = "114A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -39,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 39",
                            Number = "117A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -40,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 40",
                            Number = "120A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -41,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 41",
                            Number = "123A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -42,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 42",
                            Number = "126A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -43,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 43",
                            Number = "129A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -44,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 44",
                            Number = "132A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -45,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 45",
                            Number = "135A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -46,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 46",
                            Number = "138A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -47,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 47",
                            Number = "141A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -48,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 48",
                            Number = "144A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -49,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 49",
                            Number = "147A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -50,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 50",
                            Number = "150A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -51,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 51",
                            Number = "153A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -52,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 52",
                            Number = "156A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -53,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 53",
                            Number = "159A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -54,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 54",
                            Number = "162A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -55,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 55",
                            Number = "165A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -56,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 56",
                            Number = "168A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -57,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 57",
                            Number = "171A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -58,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 58",
                            Number = "174A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -59,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 59",
                            Number = "177A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -60,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 60",
                            Number = "180A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -61,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 61",
                            Number = "183A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -62,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 62",
                            Number = "186A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -63,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 63",
                            Number = "189A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -64,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 64",
                            Number = "192A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -65,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 65",
                            Number = "195A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -66,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 66",
                            Number = "198A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -67,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 67",
                            Number = "201A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -68,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 68",
                            Number = "204A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -69,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 69",
                            Number = "207A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -70,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 70",
                            Number = "210A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -71,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 71",
                            Number = "213A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -72,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 72",
                            Number = "216A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -73,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 73",
                            Number = "219A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -74,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 74",
                            Number = "222A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -75,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 75",
                            Number = "225A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -76,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 76",
                            Number = "228A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -77,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 77",
                            Number = "231A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -78,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 78",
                            Number = "234A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -79,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 79",
                            Number = "237A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -80,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 80",
                            Number = "240A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -81,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 81",
                            Number = "243A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -82,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 82",
                            Number = "246A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -83,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 83",
                            Number = "249A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -84,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 84",
                            Number = "252A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -85,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 85",
                            Number = "255A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -86,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 86",
                            Number = "258A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -87,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 87",
                            Number = "261A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -88,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 88",
                            Number = "264A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -89,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 89",
                            Number = "267A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -90,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 90",
                            Number = "270A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -91,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 91",
                            Number = "273A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -92,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 92",
                            Number = "276A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -93,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 93",
                            Number = "279A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -94,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 94",
                            Number = "282A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -95,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 95",
                            Number = "285A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -96,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 96",
                            Number = "288A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -97,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 97",
                            Number = "291A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -98,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 98",
                            Number = "294A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -99,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 99",
                            Number = "297A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -100,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 100",
                            Number = "300A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -101,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 101",
                            Number = "303A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        });
                });

            modelBuilder.Entity("MyGameStore.Model.Person", b =>
                {
                    b.HasOne("MyGameStore.Model.Store", "Employer")
                        .WithMany("Employees")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("MyGameStore.Model.Store", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
