// <auto-generated />
using System;
using AP.MyGameStore.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyGameStore.Migrations
{
    [DbContext(typeof(MyGameStoreContext))]
    partial class MyGameStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyGameStore.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EmailAddress");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("tblPeople", "Person");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Allan.Jones24@gmail.com",
                            EmployerId = -9,
                            FirstName = "Lana",
                            Gender = 1,
                            LastName = "Hegmann"
                        },
                        new
                        {
                            Id = -2,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hilbert_Skiles@hotmail.com",
                            EmployerId = -23,
                            FirstName = "Julie",
                            Gender = 1,
                            LastName = "Jacobs"
                        },
                        new
                        {
                            Id = -3,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dee_Kunze40@gmail.com",
                            EmployerId = -62,
                            FirstName = "Frances",
                            Gender = 1,
                            LastName = "Zieme"
                        },
                        new
                        {
                            Id = -4,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dessie_Torphy@yahoo.com",
                            EmployerId = -59,
                            FirstName = "Roy",
                            Gender = 0,
                            LastName = "Bruen"
                        },
                        new
                        {
                            Id = -5,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Beverly.Hegmann81@hotmail.com",
                            EmployerId = -7,
                            FirstName = "Alberta",
                            Gender = 1,
                            LastName = "Vandervort"
                        },
                        new
                        {
                            Id = -6,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lamar.Block@hotmail.com",
                            EmployerId = -46,
                            FirstName = "Travis",
                            Gender = 0,
                            LastName = "Kemmer"
                        },
                        new
                        {
                            Id = -7,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lia.Collins@yahoo.com",
                            EmployerId = -19,
                            FirstName = "Irvin",
                            Gender = 0,
                            LastName = "Blick"
                        },
                        new
                        {
                            Id = -8,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Eleanore.West@hotmail.com",
                            EmployerId = -62,
                            FirstName = "Guillermo",
                            Gender = 0,
                            LastName = "Kessler"
                        },
                        new
                        {
                            Id = -9,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Elouise.Hintz@yahoo.com",
                            EmployerId = -58,
                            FirstName = "Elisa",
                            Gender = 1,
                            LastName = "Hoeger"
                        },
                        new
                        {
                            Id = -10,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Arch.Leannon66@yahoo.com",
                            EmployerId = -45,
                            FirstName = "Robyn",
                            Gender = 1,
                            LastName = "Watsica"
                        },
                        new
                        {
                            Id = -11,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alan_Hilll58@gmail.com",
                            EmployerId = -54,
                            FirstName = "Nathan",
                            Gender = 0,
                            LastName = "Windler"
                        },
                        new
                        {
                            Id = -12,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Colt30@yahoo.com",
                            EmployerId = -26,
                            FirstName = "Sheri",
                            Gender = 1,
                            LastName = "Stamm"
                        },
                        new
                        {
                            Id = -13,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Loy16@gmail.com",
                            EmployerId = -21,
                            FirstName = "David",
                            Gender = 0,
                            LastName = "Kohler"
                        },
                        new
                        {
                            Id = -14,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Onie.Jacobi51@gmail.com",
                            EmployerId = -34,
                            FirstName = "Marlon",
                            Gender = 0,
                            LastName = "Crona"
                        },
                        new
                        {
                            Id = -15,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Brody_Cremin@yahoo.com",
                            EmployerId = -90,
                            FirstName = "Sally",
                            Gender = 1,
                            LastName = "McCullough"
                        },
                        new
                        {
                            Id = -16,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Zion_Koss@yahoo.com",
                            EmployerId = -8,
                            FirstName = "Elias",
                            Gender = 0,
                            LastName = "Hermiston"
                        },
                        new
                        {
                            Id = -17,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mariana.Sawayn62@yahoo.com",
                            EmployerId = -47,
                            FirstName = "Marilyn",
                            Gender = 1,
                            LastName = "Dooley"
                        },
                        new
                        {
                            Id = -18,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Tania.Ryan@gmail.com",
                            EmployerId = -72,
                            FirstName = "Violet",
                            Gender = 1,
                            LastName = "Hermiston"
                        },
                        new
                        {
                            Id = -19,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Orpha_Mayert@yahoo.com",
                            EmployerId = -76,
                            FirstName = "Isabel",
                            Gender = 1,
                            LastName = "Treutel"
                        },
                        new
                        {
                            Id = -20,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kiarra_McCullough49@gmail.com",
                            EmployerId = -89,
                            FirstName = "Alberto",
                            Gender = 0,
                            LastName = "Armstrong"
                        },
                        new
                        {
                            Id = -21,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Eduardo_Bogisich@yahoo.com",
                            EmployerId = -35,
                            FirstName = "Luke",
                            Gender = 0,
                            LastName = "Brakus"
                        },
                        new
                        {
                            Id = -22,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Chris_Nitzsche28@yahoo.com",
                            EmployerId = -82,
                            FirstName = "Lloyd",
                            Gender = 0,
                            LastName = "Ebert"
                        },
                        new
                        {
                            Id = -23,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Emelia_Douglas@hotmail.com",
                            EmployerId = -56,
                            FirstName = "Eleanor",
                            Gender = 1,
                            LastName = "Gleichner"
                        },
                        new
                        {
                            Id = -24,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Keshaun.Pacocha@yahoo.com",
                            EmployerId = -41,
                            FirstName = "Santiago",
                            Gender = 0,
                            LastName = "Hand"
                        },
                        new
                        {
                            Id = -25,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Janis99@gmail.com",
                            EmployerId = -84,
                            FirstName = "Pablo",
                            Gender = 0,
                            LastName = "Dooley"
                        },
                        new
                        {
                            Id = -26,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hunter.Leannon@gmail.com",
                            EmployerId = -95,
                            FirstName = "Lora",
                            Gender = 1,
                            LastName = "Abbott"
                        },
                        new
                        {
                            Id = -27,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Katheryn_Bernier@gmail.com",
                            EmployerId = -64,
                            FirstName = "Lynne",
                            Gender = 1,
                            LastName = "Kessler"
                        },
                        new
                        {
                            Id = -28,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dennis_Mayer@yahoo.com",
                            EmployerId = -81,
                            FirstName = "Doug",
                            Gender = 0,
                            LastName = "Wuckert"
                        },
                        new
                        {
                            Id = -29,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Beulah.Swift82@yahoo.com",
                            EmployerId = -27,
                            FirstName = "Barbara",
                            Gender = 1,
                            LastName = "Beahan"
                        },
                        new
                        {
                            Id = -30,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mckenna31@gmail.com",
                            EmployerId = -51,
                            FirstName = "Domingo",
                            Gender = 0,
                            LastName = "D'Amore"
                        },
                        new
                        {
                            Id = -31,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jared97@gmail.com",
                            EmployerId = -60,
                            FirstName = "Nicholas",
                            Gender = 0,
                            LastName = "Hoppe"
                        },
                        new
                        {
                            Id = -32,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jayme_Sporer67@hotmail.com",
                            EmployerId = -32,
                            FirstName = "Joel",
                            Gender = 0,
                            LastName = "Lang"
                        },
                        new
                        {
                            Id = -33,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Arely.Schaden31@hotmail.com",
                            EmployerId = -43,
                            FirstName = "Gene",
                            Gender = 0,
                            LastName = "O'Conner"
                        },
                        new
                        {
                            Id = -34,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Devan31@gmail.com",
                            EmployerId = -5,
                            FirstName = "Timothy",
                            Gender = 0,
                            LastName = "Schneider"
                        },
                        new
                        {
                            Id = -35,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Heather67@yahoo.com",
                            EmployerId = -53,
                            FirstName = "Anna",
                            Gender = 1,
                            LastName = "Bahringer"
                        },
                        new
                        {
                            Id = -36,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Sedrick_Balistreri@hotmail.com",
                            EmployerId = -13,
                            FirstName = "Veronica",
                            Gender = 1,
                            LastName = "Stehr"
                        },
                        new
                        {
                            Id = -37,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Monserrate_Reinger@yahoo.com",
                            EmployerId = -54,
                            FirstName = "Dennis",
                            Gender = 0,
                            LastName = "Rempel"
                        },
                        new
                        {
                            Id = -38,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Carmela45@gmail.com",
                            EmployerId = -20,
                            FirstName = "Carrie",
                            Gender = 1,
                            LastName = "Rippin"
                        },
                        new
                        {
                            Id = -39,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Maudie49@hotmail.com",
                            EmployerId = -94,
                            FirstName = "Victor",
                            Gender = 0,
                            LastName = "Kuhlman"
                        },
                        new
                        {
                            Id = -40,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Aaliyah_Torphy@yahoo.com",
                            EmployerId = -10,
                            FirstName = "Boyd",
                            Gender = 0,
                            LastName = "Rippin"
                        },
                        new
                        {
                            Id = -41,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Sasha_Jenkins@gmail.com",
                            EmployerId = -75,
                            FirstName = "Shane",
                            Gender = 0,
                            LastName = "Schaefer"
                        },
                        new
                        {
                            Id = -42,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Francesca_Mueller@yahoo.com",
                            EmployerId = -28,
                            FirstName = "Joanne",
                            Gender = 1,
                            LastName = "Krajcik"
                        },
                        new
                        {
                            Id = -43,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Timmy77@gmail.com",
                            EmployerId = -48,
                            FirstName = "Neil",
                            Gender = 0,
                            LastName = "Bruen"
                        },
                        new
                        {
                            Id = -44,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jovan.Lang@yahoo.com",
                            EmployerId = -92,
                            FirstName = "Fannie",
                            Gender = 1,
                            LastName = "Rohan"
                        },
                        new
                        {
                            Id = -45,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Therese.Roob79@gmail.com",
                            EmployerId = -58,
                            FirstName = "Henrietta",
                            Gender = 1,
                            LastName = "Wyman"
                        },
                        new
                        {
                            Id = -46,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Leonie.Koch26@hotmail.com",
                            EmployerId = -75,
                            FirstName = "Andrew",
                            Gender = 0,
                            LastName = "Reilly"
                        },
                        new
                        {
                            Id = -47,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Baylee_Mills@hotmail.com",
                            EmployerId = -52,
                            FirstName = "Carmen",
                            Gender = 1,
                            LastName = "Rutherford"
                        },
                        new
                        {
                            Id = -48,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Demarcus.Hane@hotmail.com",
                            EmployerId = -5,
                            FirstName = "Micheal",
                            Gender = 0,
                            LastName = "Weber"
                        },
                        new
                        {
                            Id = -49,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Madyson_Feest@gmail.com",
                            EmployerId = -38,
                            FirstName = "Robyn",
                            Gender = 1,
                            LastName = "Rippin"
                        },
                        new
                        {
                            Id = -50,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Idell_Tromp@gmail.com",
                            EmployerId = -19,
                            FirstName = "Bertha",
                            Gender = 1,
                            LastName = "Fadel"
                        },
                        new
                        {
                            Id = -51,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lilliana.Quitzon@gmail.com",
                            EmployerId = -45,
                            FirstName = "Sarah",
                            Gender = 1,
                            LastName = "Moen"
                        },
                        new
                        {
                            Id = -52,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Niko.Satterfield62@yahoo.com",
                            EmployerId = -41,
                            FirstName = "Eula",
                            Gender = 1,
                            LastName = "Collier"
                        },
                        new
                        {
                            Id = -53,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Catalina_Russel82@gmail.com",
                            EmployerId = -42,
                            FirstName = "Lois",
                            Gender = 1,
                            LastName = "Jenkins"
                        },
                        new
                        {
                            Id = -54,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Samir6@yahoo.com",
                            EmployerId = -21,
                            FirstName = "Angel",
                            Gender = 1,
                            LastName = "Murphy"
                        },
                        new
                        {
                            Id = -55,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Cydney_Okuneva58@yahoo.com",
                            EmployerId = -62,
                            FirstName = "Angelo",
                            Gender = 0,
                            LastName = "Kuvalis"
                        },
                        new
                        {
                            Id = -56,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mertie.Fahey61@hotmail.com",
                            EmployerId = -23,
                            FirstName = "Jennie",
                            Gender = 1,
                            LastName = "Stanton"
                        },
                        new
                        {
                            Id = -57,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Clark.McCullough@hotmail.com",
                            EmployerId = -16,
                            FirstName = "Randall",
                            Gender = 0,
                            LastName = "Donnelly"
                        },
                        new
                        {
                            Id = -58,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Tyler.Gusikowski@gmail.com",
                            EmployerId = -43,
                            FirstName = "Tommie",
                            Gender = 0,
                            LastName = "Ferry"
                        },
                        new
                        {
                            Id = -59,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Eliezer32@hotmail.com",
                            EmployerId = -7,
                            FirstName = "Randall",
                            Gender = 0,
                            LastName = "Cummerata"
                        },
                        new
                        {
                            Id = -60,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Stefanie88@yahoo.com",
                            EmployerId = -71,
                            FirstName = "Christy",
                            Gender = 1,
                            LastName = "Treutel"
                        },
                        new
                        {
                            Id = -61,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Morgan89@yahoo.com",
                            EmployerId = -36,
                            FirstName = "Monique",
                            Gender = 1,
                            LastName = "Bailey"
                        },
                        new
                        {
                            Id = -62,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kade47@hotmail.com",
                            EmployerId = -27,
                            FirstName = "Randal",
                            Gender = 0,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = -63,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Cora.Zboncak90@gmail.com",
                            EmployerId = -46,
                            FirstName = "Beulah",
                            Gender = 1,
                            LastName = "Renner"
                        },
                        new
                        {
                            Id = -64,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kory_Buckridge@gmail.com",
                            EmployerId = -2,
                            FirstName = "Andrea",
                            Gender = 1,
                            LastName = "Kulas"
                        },
                        new
                        {
                            Id = -65,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lilliana72@gmail.com",
                            EmployerId = -98,
                            FirstName = "Erin",
                            Gender = 1,
                            LastName = "Kling"
                        },
                        new
                        {
                            Id = -66,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Linda.Jast86@gmail.com",
                            EmployerId = -57,
                            FirstName = "Nathan",
                            Gender = 0,
                            LastName = "Dietrich"
                        },
                        new
                        {
                            Id = -67,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ellen_Pacocha@gmail.com",
                            EmployerId = -64,
                            FirstName = "Sue",
                            Gender = 1,
                            LastName = "Hoppe"
                        },
                        new
                        {
                            Id = -68,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rosie19@yahoo.com",
                            EmployerId = -77,
                            FirstName = "Raul",
                            Gender = 0,
                            LastName = "Stanton"
                        },
                        new
                        {
                            Id = -69,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Garland_Volkman@hotmail.com",
                            EmployerId = -62,
                            FirstName = "Warren",
                            Gender = 0,
                            LastName = "Wuckert"
                        },
                        new
                        {
                            Id = -70,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jazmin84@gmail.com",
                            EmployerId = -67,
                            FirstName = "Teri",
                            Gender = 1,
                            LastName = "Casper"
                        },
                        new
                        {
                            Id = -71,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mark26@hotmail.com",
                            EmployerId = -80,
                            FirstName = "Kellie",
                            Gender = 1,
                            LastName = "Morissette"
                        },
                        new
                        {
                            Id = -72,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rosamond_Kiehn@hotmail.com",
                            EmployerId = -79,
                            FirstName = "Dean",
                            Gender = 0,
                            LastName = "Herman"
                        },
                        new
                        {
                            Id = -73,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Felipe.Powlowski@gmail.com",
                            EmployerId = -20,
                            FirstName = "Raul",
                            Gender = 0,
                            LastName = "Lind"
                        },
                        new
                        {
                            Id = -74,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Luigi_Boyle71@yahoo.com",
                            EmployerId = -32,
                            FirstName = "Sandra",
                            Gender = 1,
                            LastName = "Dooley"
                        },
                        new
                        {
                            Id = -75,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Gerson.Gislason@hotmail.com",
                            EmployerId = -95,
                            FirstName = "Ed",
                            Gender = 0,
                            LastName = "Hoeger"
                        },
                        new
                        {
                            Id = -76,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Adelia.Schowalter1@yahoo.com",
                            EmployerId = -29,
                            FirstName = "Laverne",
                            Gender = 1,
                            LastName = "Sanford"
                        },
                        new
                        {
                            Id = -77,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Julia.Corwin18@hotmail.com",
                            EmployerId = -37,
                            FirstName = "Derrick",
                            Gender = 0,
                            LastName = "Von"
                        },
                        new
                        {
                            Id = -78,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Furman8@gmail.com",
                            EmployerId = -89,
                            FirstName = "Jeremy",
                            Gender = 0,
                            LastName = "Lang"
                        },
                        new
                        {
                            Id = -79,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Gerson_Huel@gmail.com",
                            EmployerId = -39,
                            FirstName = "Natalie",
                            Gender = 1,
                            LastName = "Bergnaum"
                        },
                        new
                        {
                            Id = -80,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rosalia.Collier28@gmail.com",
                            EmployerId = -20,
                            FirstName = "Kristine",
                            Gender = 1,
                            LastName = "Upton"
                        },
                        new
                        {
                            Id = -81,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Valentin.Schowalter44@gmail.com",
                            EmployerId = -90,
                            FirstName = "Darrin",
                            Gender = 0,
                            LastName = "Feest"
                        },
                        new
                        {
                            Id = -82,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Joel.Robel85@gmail.com",
                            EmployerId = -67,
                            FirstName = "Hugo",
                            Gender = 0,
                            LastName = "Walter"
                        },
                        new
                        {
                            Id = -83,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Eldora0@gmail.com",
                            EmployerId = -31,
                            FirstName = "Woodrow",
                            Gender = 0,
                            LastName = "Schoen"
                        },
                        new
                        {
                            Id = -84,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Terry21@yahoo.com",
                            EmployerId = -78,
                            FirstName = "Wesley",
                            Gender = 0,
                            LastName = "Bahringer"
                        },
                        new
                        {
                            Id = -85,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Trisha69@yahoo.com",
                            EmployerId = -75,
                            FirstName = "Randolph",
                            Gender = 0,
                            LastName = "Schowalter"
                        },
                        new
                        {
                            Id = -86,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Callie_Tremblay@hotmail.com",
                            EmployerId = -24,
                            FirstName = "Jamie",
                            Gender = 0,
                            LastName = "Green"
                        },
                        new
                        {
                            Id = -87,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Charlene.Mueller76@gmail.com",
                            EmployerId = -80,
                            FirstName = "Maggie",
                            Gender = 1,
                            LastName = "Treutel"
                        },
                        new
                        {
                            Id = -88,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Providenci.Marquardt@yahoo.com",
                            EmployerId = -25,
                            FirstName = "Tyler",
                            Gender = 0,
                            LastName = "Boyle"
                        },
                        new
                        {
                            Id = -89,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Leonora.Schuster@hotmail.com",
                            EmployerId = -38,
                            FirstName = "Kirk",
                            Gender = 0,
                            LastName = "Osinski"
                        },
                        new
                        {
                            Id = -90,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Norma.Schaefer51@hotmail.com",
                            EmployerId = -17,
                            FirstName = "Shaun",
                            Gender = 0,
                            LastName = "Wisoky"
                        },
                        new
                        {
                            Id = -91,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Harry96@hotmail.com",
                            EmployerId = -37,
                            FirstName = "Cecelia",
                            Gender = 1,
                            LastName = "Dooley"
                        },
                        new
                        {
                            Id = -92,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dillon_Bashirian@gmail.com",
                            EmployerId = -1,
                            FirstName = "Mack",
                            Gender = 0,
                            LastName = "Stracke"
                        },
                        new
                        {
                            Id = -93,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Esmeralda19@yahoo.com",
                            EmployerId = -13,
                            FirstName = "Joy",
                            Gender = 1,
                            LastName = "Stracke"
                        },
                        new
                        {
                            Id = -94,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Cletus.Nolan78@hotmail.com",
                            EmployerId = -30,
                            FirstName = "Kelly",
                            Gender = 1,
                            LastName = "Orn"
                        },
                        new
                        {
                            Id = -95,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Clark_Jacobson65@gmail.com",
                            EmployerId = -39,
                            FirstName = "Colin",
                            Gender = 0,
                            LastName = "Robel"
                        },
                        new
                        {
                            Id = -96,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Deion_Daugherty@hotmail.com",
                            EmployerId = -82,
                            FirstName = "Bertha",
                            Gender = 1,
                            LastName = "Stokes"
                        },
                        new
                        {
                            Id = -97,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Katrina.Hessel23@gmail.com",
                            EmployerId = -55,
                            FirstName = "Jesse",
                            Gender = 0,
                            LastName = "Kozey"
                        },
                        new
                        {
                            Id = -98,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Tyrel.Blick@yahoo.com",
                            EmployerId = -71,
                            FirstName = "Miranda",
                            Gender = 1,
                            LastName = "Lang"
                        },
                        new
                        {
                            Id = -99,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Cali.Marquardt@hotmail.com",
                            EmployerId = -33,
                            FirstName = "Nadine",
                            Gender = 1,
                            LastName = "Schuppe"
                        },
                        new
                        {
                            Id = -100,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rashawn_Romaguera@hotmail.com",
                            EmployerId = -56,
                            FirstName = "Antonio",
                            Gender = 0,
                            LastName = "Kautzer"
                        });
                });

            modelBuilder.Entity("MyGameStore.Model.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Addition")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Place");

                    b.Property<bool>("IsFranchiseStore")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tblStores", "Store");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 1",
                            Number = "3A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -2,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 2",
                            Number = "6A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -3,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 3",
                            Number = "9A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -4,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 4",
                            Number = "12A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -5,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 5",
                            Number = "15A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -6,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 6",
                            Number = "18A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -7,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 7",
                            Number = "21A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -8,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 8",
                            Number = "24A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -9,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 9",
                            Number = "27A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -10,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 10",
                            Number = "30A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -11,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 11",
                            Number = "33A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -12,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 12",
                            Number = "36A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -13,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 13",
                            Number = "39A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -14,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 14",
                            Number = "42A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -15,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 15",
                            Number = "45A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -16,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 16",
                            Number = "48A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -17,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 17",
                            Number = "51A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -18,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 18",
                            Number = "54A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -19,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 19",
                            Number = "57A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -20,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 20",
                            Number = "60A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -21,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 21",
                            Number = "63A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -22,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 22",
                            Number = "66A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -23,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 23",
                            Number = "69A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -24,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 24",
                            Number = "72A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -25,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 25",
                            Number = "75A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -26,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 26",
                            Number = "78A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -27,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 27",
                            Number = "81A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -28,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 28",
                            Number = "84A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -29,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 29",
                            Number = "87A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -30,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 30",
                            Number = "90A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -31,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 31",
                            Number = "93A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -32,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 32",
                            Number = "96A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -33,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 33",
                            Number = "99A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -34,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 34",
                            Number = "102A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -35,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 35",
                            Number = "105A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -36,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 36",
                            Number = "108A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -37,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 37",
                            Number = "111A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -38,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 38",
                            Number = "114A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -39,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 39",
                            Number = "117A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -40,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 40",
                            Number = "120A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -41,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 41",
                            Number = "123A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -42,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 42",
                            Number = "126A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -43,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 43",
                            Number = "129A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -44,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 44",
                            Number = "132A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -45,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 45",
                            Number = "135A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -46,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 46",
                            Number = "138A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -47,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 47",
                            Number = "141A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -48,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 48",
                            Number = "144A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -49,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 49",
                            Number = "147A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -50,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 50",
                            Number = "150A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -51,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 51",
                            Number = "153A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -52,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 52",
                            Number = "156A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -53,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 53",
                            Number = "159A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -54,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 54",
                            Number = "162A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -55,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 55",
                            Number = "165A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -56,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 56",
                            Number = "168A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -57,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 57",
                            Number = "171A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -58,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 58",
                            Number = "174A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -59,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 59",
                            Number = "177A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -60,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 60",
                            Number = "180A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -61,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 61",
                            Number = "183A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -62,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 62",
                            Number = "186A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -63,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 63",
                            Number = "189A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -64,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 64",
                            Number = "192A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -65,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 65",
                            Number = "195A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -66,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 66",
                            Number = "198A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -67,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 67",
                            Number = "201A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -68,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 68",
                            Number = "204A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -69,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 69",
                            Number = "207A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -70,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 70",
                            Number = "210A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -71,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 71",
                            Number = "213A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -72,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 72",
                            Number = "216A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -73,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 73",
                            Number = "219A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -74,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 74",
                            Number = "222A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -75,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 75",
                            Number = "225A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -76,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 76",
                            Number = "228A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -77,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 77",
                            Number = "231A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -78,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 78",
                            Number = "234A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -79,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 79",
                            Number = "237A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -80,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 80",
                            Number = "240A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -81,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 81",
                            Number = "243A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -82,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 82",
                            Number = "246A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -83,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 83",
                            Number = "249A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -84,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 84",
                            Number = "252A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -85,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 85",
                            Number = "255A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -86,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 86",
                            Number = "258A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -87,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 87",
                            Number = "261A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -88,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 88",
                            Number = "264A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -89,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 89",
                            Number = "267A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -90,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 90",
                            Number = "270A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -91,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 91",
                            Number = "273A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -92,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 92",
                            Number = "276A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -93,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 93",
                            Number = "279A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -94,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 94",
                            Number = "282A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -95,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 95",
                            Number = "285A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -96,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 96",
                            Number = "288A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -97,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 97",
                            Number = "291A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -98,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 98",
                            Number = "294A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -99,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 99",
                            Number = "297A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -100,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 100",
                            Number = "300A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -101,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 101",
                            Number = "303A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        });
                });

            modelBuilder.Entity("MyGameStore.Model.Person", b =>
                {
                    b.HasOne("MyGameStore.Model.Store", "Employer")
                        .WithMany("Employees")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("MyGameStore.Model.Store", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
