// <auto-generated />
using System;
using AP.MyGameStore.DAL.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AP.MyGameStore.DAL.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20231207103827_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AP.MyGameStore.DAL.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployerId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("tblPeople", "Store");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kendall.Gutkowski@hotmail.com",
                            EmployerId = -55,
                            FirstName = "Arturo",
                            Gender = 0,
                            LastName = "Okuneva"
                        },
                        new
                        {
                            Id = -2,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Keira.Dietrich30@hotmail.com",
                            EmployerId = -61,
                            FirstName = "Ian",
                            Gender = 0,
                            LastName = "Funk"
                        },
                        new
                        {
                            Id = -3,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Leda_Kub6@hotmail.com",
                            EmployerId = -15,
                            FirstName = "Hattie",
                            Gender = 1,
                            LastName = "Wilkinson"
                        },
                        new
                        {
                            Id = -4,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lexus.Stamm@gmail.com",
                            EmployerId = -84,
                            FirstName = "Ernesto",
                            Gender = 0,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = -5,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Syble_Runolfsdottir@hotmail.com",
                            EmployerId = -54,
                            FirstName = "Ricky",
                            Gender = 0,
                            LastName = "Hane"
                        },
                        new
                        {
                            Id = -6,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lindsey.Jacobi@gmail.com",
                            EmployerId = -63,
                            FirstName = "Carlos",
                            Gender = 0,
                            LastName = "Larson"
                        },
                        new
                        {
                            Id = -7,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ryley_Lowe26@hotmail.com",
                            EmployerId = -19,
                            FirstName = "Gilberto",
                            Gender = 0,
                            LastName = "Ledner"
                        },
                        new
                        {
                            Id = -8,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Cole_Nader10@hotmail.com",
                            EmployerId = -90,
                            FirstName = "Ricardo",
                            Gender = 0,
                            LastName = "Haag"
                        },
                        new
                        {
                            Id = -9,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lyda8@gmail.com",
                            EmployerId = -21,
                            FirstName = "Patty",
                            Gender = 1,
                            LastName = "Krajcik"
                        },
                        new
                        {
                            Id = -10,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ora89@gmail.com",
                            EmployerId = -68,
                            FirstName = "Franklin",
                            Gender = 0,
                            LastName = "Kreiger"
                        },
                        new
                        {
                            Id = -11,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Brigitte60@hotmail.com",
                            EmployerId = -18,
                            FirstName = "Jeffery",
                            Gender = 0,
                            LastName = "Batz"
                        },
                        new
                        {
                            Id = -12,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Elissa.Davis@gmail.com",
                            EmployerId = -27,
                            FirstName = "Melanie",
                            Gender = 1,
                            LastName = "Witting"
                        },
                        new
                        {
                            Id = -13,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Clementine68@yahoo.com",
                            EmployerId = -53,
                            FirstName = "Anne",
                            Gender = 1,
                            LastName = "Veum"
                        },
                        new
                        {
                            Id = -14,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Elvis.Hayes@yahoo.com",
                            EmployerId = -64,
                            FirstName = "Candice",
                            Gender = 1,
                            LastName = "Lehner"
                        },
                        new
                        {
                            Id = -15,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Talia_Sporer@hotmail.com",
                            EmployerId = -52,
                            FirstName = "Lena",
                            Gender = 1,
                            LastName = "Auer"
                        },
                        new
                        {
                            Id = -16,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Serena_Lockman@gmail.com",
                            EmployerId = -33,
                            FirstName = "Louis",
                            Gender = 0,
                            LastName = "Quitzon"
                        },
                        new
                        {
                            Id = -17,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Madisen_Daniel28@yahoo.com",
                            EmployerId = -86,
                            FirstName = "Willard",
                            Gender = 0,
                            LastName = "Daugherty"
                        },
                        new
                        {
                            Id = -18,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Theresia.Mraz31@hotmail.com",
                            EmployerId = -65,
                            FirstName = "Terrance",
                            Gender = 0,
                            LastName = "Jacobi"
                        },
                        new
                        {
                            Id = -19,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lue67@yahoo.com",
                            EmployerId = -10,
                            FirstName = "Jasmine",
                            Gender = 1,
                            LastName = "Rosenbaum"
                        },
                        new
                        {
                            Id = -20,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Brisa.Lowe@yahoo.com",
                            EmployerId = -68,
                            FirstName = "Samuel",
                            Gender = 0,
                            LastName = "Fisher"
                        },
                        new
                        {
                            Id = -21,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kian36@yahoo.com",
                            EmployerId = -53,
                            FirstName = "Patsy",
                            Gender = 1,
                            LastName = "Hand"
                        },
                        new
                        {
                            Id = -22,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jaylan91@yahoo.com",
                            EmployerId = -84,
                            FirstName = "Tasha",
                            Gender = 1,
                            LastName = "Johnston"
                        },
                        new
                        {
                            Id = -23,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mariela68@gmail.com",
                            EmployerId = -97,
                            FirstName = "Gustavo",
                            Gender = 0,
                            LastName = "Nienow"
                        },
                        new
                        {
                            Id = -24,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Bailee61@gmail.com",
                            EmployerId = -73,
                            FirstName = "Michele",
                            Gender = 1,
                            LastName = "Klein"
                        },
                        new
                        {
                            Id = -25,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Douglas_Sawayn95@gmail.com",
                            EmployerId = -83,
                            FirstName = "Ramon",
                            Gender = 0,
                            LastName = "Bashirian"
                        },
                        new
                        {
                            Id = -26,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Catalina.Douglas75@hotmail.com",
                            EmployerId = -20,
                            FirstName = "Alonzo",
                            Gender = 0,
                            LastName = "Buckridge"
                        },
                        new
                        {
                            Id = -27,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Khalil5@yahoo.com",
                            EmployerId = -88,
                            FirstName = "Gilberto",
                            Gender = 0,
                            LastName = "Kris"
                        },
                        new
                        {
                            Id = -28,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lew.Ullrich@yahoo.com",
                            EmployerId = -63,
                            FirstName = "Julio",
                            Gender = 0,
                            LastName = "Kulas"
                        },
                        new
                        {
                            Id = -29,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hershel.OReilly34@gmail.com",
                            EmployerId = -40,
                            FirstName = "Nina",
                            Gender = 1,
                            LastName = "Conn"
                        },
                        new
                        {
                            Id = -30,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Leola87@gmail.com",
                            EmployerId = -89,
                            FirstName = "Olive",
                            Gender = 1,
                            LastName = "Hermiston"
                        },
                        new
                        {
                            Id = -31,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Shanel.Reichel78@hotmail.com",
                            EmployerId = -87,
                            FirstName = "Sharon",
                            Gender = 1,
                            LastName = "Blick"
                        },
                        new
                        {
                            Id = -32,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kenton83@yahoo.com",
                            EmployerId = -6,
                            FirstName = "Shaun",
                            Gender = 0,
                            LastName = "Effertz"
                        },
                        new
                        {
                            Id = -33,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mose.Macejkovic26@gmail.com",
                            EmployerId = -64,
                            FirstName = "Peter",
                            Gender = 0,
                            LastName = "Lowe"
                        },
                        new
                        {
                            Id = -34,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Cristobal37@yahoo.com",
                            EmployerId = -60,
                            FirstName = "Esther",
                            Gender = 1,
                            LastName = "Douglas"
                        },
                        new
                        {
                            Id = -35,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mertie_Morissette@gmail.com",
                            EmployerId = -59,
                            FirstName = "Anna",
                            Gender = 1,
                            LastName = "Nolan"
                        },
                        new
                        {
                            Id = -36,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Josefina57@hotmail.com",
                            EmployerId = -42,
                            FirstName = "Jackie",
                            Gender = 0,
                            LastName = "Kris"
                        },
                        new
                        {
                            Id = -37,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Holden.Tillman@gmail.com",
                            EmployerId = -68,
                            FirstName = "Sylvester",
                            Gender = 0,
                            LastName = "Wolf"
                        },
                        new
                        {
                            Id = -38,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Wilma.Jones@gmail.com",
                            EmployerId = -12,
                            FirstName = "Clarence",
                            Gender = 0,
                            LastName = "Hartmann"
                        },
                        new
                        {
                            Id = -39,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Willie66@hotmail.com",
                            EmployerId = -61,
                            FirstName = "George",
                            Gender = 0,
                            LastName = "Abbott"
                        },
                        new
                        {
                            Id = -40,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Augustus_OHara3@hotmail.com",
                            EmployerId = -89,
                            FirstName = "Freda",
                            Gender = 1,
                            LastName = "Erdman"
                        },
                        new
                        {
                            Id = -41,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Anjali_Cormier44@gmail.com",
                            EmployerId = -1,
                            FirstName = "Paulette",
                            Gender = 1,
                            LastName = "Raynor"
                        },
                        new
                        {
                            Id = -42,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Krystal53@hotmail.com",
                            EmployerId = -57,
                            FirstName = "Fannie",
                            Gender = 1,
                            LastName = "Runolfsdottir"
                        },
                        new
                        {
                            Id = -43,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Queenie6@gmail.com",
                            EmployerId = -61,
                            FirstName = "Jonathan",
                            Gender = 0,
                            LastName = "Bayer"
                        },
                        new
                        {
                            Id = -44,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kitty_Kovacek@gmail.com",
                            EmployerId = -48,
                            FirstName = "Jim",
                            Gender = 0,
                            LastName = "Gibson"
                        },
                        new
                        {
                            Id = -45,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jacinthe59@hotmail.com",
                            EmployerId = -32,
                            FirstName = "Darla",
                            Gender = 1,
                            LastName = "Nicolas"
                        },
                        new
                        {
                            Id = -46,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rickie72@gmail.com",
                            EmployerId = -94,
                            FirstName = "Roderick",
                            Gender = 0,
                            LastName = "Leannon"
                        },
                        new
                        {
                            Id = -47,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Cathryn_Green99@hotmail.com",
                            EmployerId = -100,
                            FirstName = "Veronica",
                            Gender = 1,
                            LastName = "Kunze"
                        },
                        new
                        {
                            Id = -48,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Isac_VonRueden@yahoo.com",
                            EmployerId = -62,
                            FirstName = "Ramona",
                            Gender = 1,
                            LastName = "Witting"
                        },
                        new
                        {
                            Id = -49,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Bulah58@yahoo.com",
                            EmployerId = -11,
                            FirstName = "Kimberly",
                            Gender = 1,
                            LastName = "Heller"
                        },
                        new
                        {
                            Id = -50,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lavinia.Legros@yahoo.com",
                            EmployerId = -71,
                            FirstName = "Belinda",
                            Gender = 1,
                            LastName = "Hackett"
                        },
                        new
                        {
                            Id = -51,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Tiara.Rolfson58@gmail.com",
                            EmployerId = -45,
                            FirstName = "Norma",
                            Gender = 1,
                            LastName = "Reichert"
                        },
                        new
                        {
                            Id = -52,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Cleora_Boyer23@yahoo.com",
                            EmployerId = -79,
                            FirstName = "Edmund",
                            Gender = 0,
                            LastName = "Streich"
                        },
                        new
                        {
                            Id = -53,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Grayce89@gmail.com",
                            EmployerId = -12,
                            FirstName = "Julia",
                            Gender = 1,
                            LastName = "Cartwright"
                        },
                        new
                        {
                            Id = -54,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Fredy_Schroeder@yahoo.com",
                            EmployerId = -85,
                            FirstName = "Annie",
                            Gender = 1,
                            LastName = "Thiel"
                        },
                        new
                        {
                            Id = -55,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dovie.Fahey68@gmail.com",
                            EmployerId = -66,
                            FirstName = "Anna",
                            Gender = 1,
                            LastName = "Gibson"
                        },
                        new
                        {
                            Id = -56,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Orville_Klein27@hotmail.com",
                            EmployerId = -45,
                            FirstName = "Rudy",
                            Gender = 0,
                            LastName = "Reynolds"
                        },
                        new
                        {
                            Id = -57,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ericka79@hotmail.com",
                            EmployerId = -29,
                            FirstName = "Jan",
                            Gender = 0,
                            LastName = "Upton"
                        },
                        new
                        {
                            Id = -58,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Julie.Skiles21@yahoo.com",
                            EmployerId = -47,
                            FirstName = "Jody",
                            Gender = 0,
                            LastName = "Wunsch"
                        },
                        new
                        {
                            Id = -59,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Aurelio.Jenkins80@yahoo.com",
                            EmployerId = -80,
                            FirstName = "Lila",
                            Gender = 1,
                            LastName = "Bernier"
                        },
                        new
                        {
                            Id = -60,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hardy_Stanton@gmail.com",
                            EmployerId = -3,
                            FirstName = "Lee",
                            Gender = 0,
                            LastName = "Johns"
                        },
                        new
                        {
                            Id = -61,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jessika16@yahoo.com",
                            EmployerId = -100,
                            FirstName = "Milton",
                            Gender = 0,
                            LastName = "Beer"
                        },
                        new
                        {
                            Id = -62,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ken_Collins@hotmail.com",
                            EmployerId = -69,
                            FirstName = "Jeanette",
                            Gender = 1,
                            LastName = "Kiehn"
                        },
                        new
                        {
                            Id = -63,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Armand35@yahoo.com",
                            EmployerId = -71,
                            FirstName = "Vanessa",
                            Gender = 1,
                            LastName = "Skiles"
                        },
                        new
                        {
                            Id = -64,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Norma_Crooks76@hotmail.com",
                            EmployerId = -92,
                            FirstName = "Lee",
                            Gender = 0,
                            LastName = "Klocko"
                        },
                        new
                        {
                            Id = -65,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rocio_Rowe40@hotmail.com",
                            EmployerId = -42,
                            FirstName = "Beth",
                            Gender = 1,
                            LastName = "Luettgen"
                        },
                        new
                        {
                            Id = -66,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Keely79@yahoo.com",
                            EmployerId = -18,
                            FirstName = "Brent",
                            Gender = 0,
                            LastName = "Hintz"
                        },
                        new
                        {
                            Id = -67,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Brandt59@gmail.com",
                            EmployerId = -48,
                            FirstName = "Andrea",
                            Gender = 1,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = -68,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Milan77@gmail.com",
                            EmployerId = -80,
                            FirstName = "Edith",
                            Gender = 1,
                            LastName = "Steuber"
                        },
                        new
                        {
                            Id = -69,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Adam_Reynolds@hotmail.com",
                            EmployerId = -84,
                            FirstName = "Ruth",
                            Gender = 1,
                            LastName = "Hickle"
                        },
                        new
                        {
                            Id = -70,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jerome75@gmail.com",
                            EmployerId = -48,
                            FirstName = "Daniel",
                            Gender = 0,
                            LastName = "Schultz"
                        },
                        new
                        {
                            Id = -71,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Bertrand.Herzog98@gmail.com",
                            EmployerId = -84,
                            FirstName = "Christopher",
                            Gender = 0,
                            LastName = "O'Connell"
                        },
                        new
                        {
                            Id = -72,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jane.Doyle@yahoo.com",
                            EmployerId = -91,
                            FirstName = "Gayle",
                            Gender = 1,
                            LastName = "Barrows"
                        },
                        new
                        {
                            Id = -73,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Consuelo.Pouros71@hotmail.com",
                            EmployerId = -98,
                            FirstName = "Jana",
                            Gender = 1,
                            LastName = "Raynor"
                        },
                        new
                        {
                            Id = -74,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Connie.Labadie53@hotmail.com",
                            EmployerId = -71,
                            FirstName = "Dorothy",
                            Gender = 1,
                            LastName = "Hudson"
                        },
                        new
                        {
                            Id = -75,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Brendon69@gmail.com",
                            EmployerId = -56,
                            FirstName = "Jessie",
                            Gender = 0,
                            LastName = "Hettinger"
                        },
                        new
                        {
                            Id = -76,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Maurice.Lehner@yahoo.com",
                            EmployerId = -36,
                            FirstName = "Armando",
                            Gender = 0,
                            LastName = "Bauch"
                        },
                        new
                        {
                            Id = -77,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jacky54@gmail.com",
                            EmployerId = -4,
                            FirstName = "Gladys",
                            Gender = 1,
                            LastName = "Mayert"
                        },
                        new
                        {
                            Id = -78,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Manuel.Corwin79@hotmail.com",
                            EmployerId = -79,
                            FirstName = "Josh",
                            Gender = 0,
                            LastName = "Windler"
                        },
                        new
                        {
                            Id = -79,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Keshaun6@hotmail.com",
                            EmployerId = -28,
                            FirstName = "Margaret",
                            Gender = 1,
                            LastName = "Towne"
                        },
                        new
                        {
                            Id = -80,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Willy19@gmail.com",
                            EmployerId = -22,
                            FirstName = "Marianne",
                            Gender = 1,
                            LastName = "Altenwerth"
                        },
                        new
                        {
                            Id = -81,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Leila14@yahoo.com",
                            EmployerId = -93,
                            FirstName = "Olive",
                            Gender = 1,
                            LastName = "Waelchi"
                        },
                        new
                        {
                            Id = -82,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jane.Donnelly@yahoo.com",
                            EmployerId = -98,
                            FirstName = "Mitchell",
                            Gender = 0,
                            LastName = "Marquardt"
                        },
                        new
                        {
                            Id = -83,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Anastasia.Watsica16@gmail.com",
                            EmployerId = -26,
                            FirstName = "Kristi",
                            Gender = 1,
                            LastName = "Padberg"
                        },
                        new
                        {
                            Id = -84,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Laurence32@yahoo.com",
                            EmployerId = -12,
                            FirstName = "Wilson",
                            Gender = 0,
                            LastName = "Sipes"
                        },
                        new
                        {
                            Id = -85,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Melany16@yahoo.com",
                            EmployerId = -56,
                            FirstName = "Mindy",
                            Gender = 1,
                            LastName = "Purdy"
                        },
                        new
                        {
                            Id = -86,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Oceane49@hotmail.com",
                            EmployerId = -97,
                            FirstName = "Veronica",
                            Gender = 1,
                            LastName = "Koch"
                        },
                        new
                        {
                            Id = -87,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Abdiel.Emard98@gmail.com",
                            EmployerId = -80,
                            FirstName = "Jean",
                            Gender = 0,
                            LastName = "Veum"
                        },
                        new
                        {
                            Id = -88,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Opal_Gutkowski@yahoo.com",
                            EmployerId = -16,
                            FirstName = "Casey",
                            Gender = 0,
                            LastName = "Roob"
                        },
                        new
                        {
                            Id = -89,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jordy_Reichert@gmail.com",
                            EmployerId = -91,
                            FirstName = "Adam",
                            Gender = 0,
                            LastName = "Rodriguez"
                        },
                        new
                        {
                            Id = -90,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Destin.Hahn70@hotmail.com",
                            EmployerId = -73,
                            FirstName = "Cynthia",
                            Gender = 1,
                            LastName = "Abbott"
                        },
                        new
                        {
                            Id = -91,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Carrie.Kovacek@hotmail.com",
                            EmployerId = -7,
                            FirstName = "Christian",
                            Gender = 0,
                            LastName = "Kilback"
                        },
                        new
                        {
                            Id = -92,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Holly99@yahoo.com",
                            EmployerId = -31,
                            FirstName = "Luis",
                            Gender = 0,
                            LastName = "Strosin"
                        },
                        new
                        {
                            Id = -93,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mateo60@gmail.com",
                            EmployerId = -49,
                            FirstName = "Christina",
                            Gender = 1,
                            LastName = "Orn"
                        },
                        new
                        {
                            Id = -94,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lelah_Johnson85@gmail.com",
                            EmployerId = -34,
                            FirstName = "Rachael",
                            Gender = 1,
                            LastName = "Harvey"
                        },
                        new
                        {
                            Id = -95,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rosamond_Glover83@yahoo.com",
                            EmployerId = -39,
                            FirstName = "Andre",
                            Gender = 0,
                            LastName = "McCullough"
                        },
                        new
                        {
                            Id = -96,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Garnet_Dickens@yahoo.com",
                            EmployerId = -6,
                            FirstName = "Ethel",
                            Gender = 1,
                            LastName = "Douglas"
                        },
                        new
                        {
                            Id = -97,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Laurence.Sauer66@gmail.com",
                            EmployerId = -70,
                            FirstName = "Amy",
                            Gender = 1,
                            LastName = "Hirthe"
                        },
                        new
                        {
                            Id = -98,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hailie_Wilderman@yahoo.com",
                            EmployerId = -10,
                            FirstName = "Colin",
                            Gender = 0,
                            LastName = "Quitzon"
                        },
                        new
                        {
                            Id = -99,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Roderick.Mayert@gmail.com",
                            EmployerId = -60,
                            FirstName = "Allan",
                            Gender = 0,
                            LastName = "Armstrong"
                        },
                        new
                        {
                            Id = -100,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kolby.Morar76@hotmail.com",
                            EmployerId = -36,
                            FirstName = "Darin",
                            Gender = 0,
                            LastName = "Yundt"
                        });
                });

            modelBuilder.Entity("AP.MyGameStore.DAL.Model.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Addition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFranchiseStore")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tblStores", "Store");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 1",
                            Number = "3A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -2,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 2",
                            Number = "6A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -3,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 3",
                            Number = "9A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -4,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 4",
                            Number = "12A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -5,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 5",
                            Number = "15A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -6,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 6",
                            Number = "18A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -7,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 7",
                            Number = "21A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -8,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 8",
                            Number = "24A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -9,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 9",
                            Number = "27A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -10,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 10",
                            Number = "30A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -11,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 11",
                            Number = "33A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -12,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 12",
                            Number = "36A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -13,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 13",
                            Number = "39A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -14,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 14",
                            Number = "42A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -15,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 15",
                            Number = "45A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -16,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 16",
                            Number = "48A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -17,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 17",
                            Number = "51A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -18,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 18",
                            Number = "54A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -19,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 19",
                            Number = "57A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -20,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 20",
                            Number = "60A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -21,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 21",
                            Number = "63A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -22,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 22",
                            Number = "66A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -23,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 23",
                            Number = "69A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -24,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 24",
                            Number = "72A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -25,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 25",
                            Number = "75A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -26,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 26",
                            Number = "78A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -27,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 27",
                            Number = "81A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -28,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 28",
                            Number = "84A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -29,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 29",
                            Number = "87A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -30,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 30",
                            Number = "90A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -31,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 31",
                            Number = "93A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -32,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 32",
                            Number = "96A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -33,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 33",
                            Number = "99A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -34,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 34",
                            Number = "102A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -35,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 35",
                            Number = "105A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -36,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 36",
                            Number = "108A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -37,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 37",
                            Number = "111A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -38,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 38",
                            Number = "114A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -39,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 39",
                            Number = "117A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -40,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 40",
                            Number = "120A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -41,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 41",
                            Number = "123A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -42,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 42",
                            Number = "126A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -43,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 43",
                            Number = "129A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -44,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 44",
                            Number = "132A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -45,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 45",
                            Number = "135A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -46,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 46",
                            Number = "138A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -47,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 47",
                            Number = "141A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -48,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 48",
                            Number = "144A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -49,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 49",
                            Number = "147A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -50,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 50",
                            Number = "150A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -51,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 51",
                            Number = "153A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -52,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 52",
                            Number = "156A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -53,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 53",
                            Number = "159A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -54,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 54",
                            Number = "162A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -55,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 55",
                            Number = "165A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -56,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 56",
                            Number = "168A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -57,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 57",
                            Number = "171A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -58,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 58",
                            Number = "174A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -59,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 59",
                            Number = "177A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -60,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 60",
                            Number = "180A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -61,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 61",
                            Number = "183A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -62,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 62",
                            Number = "186A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -63,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 63",
                            Number = "189A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -64,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 64",
                            Number = "192A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -65,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 65",
                            Number = "195A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -66,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 66",
                            Number = "198A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -67,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 67",
                            Number = "201A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -68,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 68",
                            Number = "204A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -69,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 69",
                            Number = "207A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -70,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 70",
                            Number = "210A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -71,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 71",
                            Number = "213A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -72,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 72",
                            Number = "216A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -73,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 73",
                            Number = "219A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -74,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 74",
                            Number = "222A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -75,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 75",
                            Number = "225A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -76,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 76",
                            Number = "228A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -77,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 77",
                            Number = "231A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -78,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 78",
                            Number = "234A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -79,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 79",
                            Number = "237A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -80,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 80",
                            Number = "240A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -81,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 81",
                            Number = "243A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -82,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 82",
                            Number = "246A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -83,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 83",
                            Number = "249A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -84,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 84",
                            Number = "252A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -85,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 85",
                            Number = "255A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -86,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 86",
                            Number = "258A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -87,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 87",
                            Number = "261A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -88,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 88",
                            Number = "264A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -89,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 89",
                            Number = "267A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -90,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 90",
                            Number = "270A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -91,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 91",
                            Number = "273A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -92,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 92",
                            Number = "276A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -93,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 93",
                            Number = "279A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -94,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 94",
                            Number = "282A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -95,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 95",
                            Number = "285A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -96,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 96",
                            Number = "288A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -97,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 97",
                            Number = "291A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -98,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 98",
                            Number = "294A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -99,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 99",
                            Number = "297A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -100,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 100",
                            Number = "300A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = -101,
                            Addition = "",
                            City = "Antwerp",
                            IsFranchiseStore = false,
                            Name = "Store 101",
                            Number = "303A",
                            Street = "StoreStreet",
                            Zipcode = "2000"
                        });
                });

            modelBuilder.Entity("AP.MyGameStore.DAL.Model.Person", b =>
                {
                    b.HasOne("AP.MyGameStore.DAL.Model.Store", "Employer")
                        .WithMany("Employees")
                        .HasForeignKey("EmployerId");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("AP.MyGameStore.DAL.Model.Store", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
